### ISSUE TITLE
Sync Detox Test and Instruments

### ISSUE THREAD

**Issue by oximer** [wix/DetoxInstruments#33]
How to synchronize detox test with detox instruments?
When I start a detox test, it relaunches my app killing the profile tracking record.

How to avoid it?

**Comment by LeoNatan** [comment]
Since you are relaunching your app, you will not be able to use live recording. You should start a recording in code, as described here:
https://github.com/wix/DetoxInstruments/blob/master/Documentation/DeveloperAPIReferenceProfilerObjCSwift.md

If you launch your app several times, you can use the [`continueProfilingWithConfiguration:`](https://github.com/wix/DetoxInstruments/blob/master/Documentation/DeveloperAPIReferenceDTXProfilerObjCSwift.md#continueprofilingwithconfiguration) API to continue recording in the same document.
