### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by RWOverdijk** [wix/DetoxInstruments#35]
There are no issues about this so I'll be the one to ask the dumb question for future dumb googlers like myself.

No android support? Future android support?

Thanks :D

**Comment by LeoNatan** [comment]
Hello

Not a dumb question at all. Android support is planned but there is no hard timetable other than “soon™”.

**Comment by RWOverdijk** [comment]
soon™, I like that! I'd use it, unfortunately it's trademarked. Is it like detox itself saying _"Android is nearly complete"_? :trollface: 

Anyway you make some awesome stuff. Thanks for answering!

**Comment by LeoNatan** [comment]
Let’s keep it open. 
Detox has progressed very admirably on Android and is under active development.

**Comment by rawqing** [comment]
It would be perfect if it were supported on android

**Comment by jacquesdev** [comment]
It's Hacktober, and I'd love to help to get this done. Is there anything we can do to make it happen?

**Comment by LeoNatan** [comment]
Hi @jacquesdev 

Thank you for your offer!
Since I am not really familiar with Android development, but am familiar with C++ development, I can perhaps compile a list of issues that have come to mind that would need to be answered before a POC can be attempted. I'll just throw them here in no particular order.

- Where should the bulk of the Android Profiler framework live; Java or C++? Both have merit and drawbacks. Data marshaling from Java to C++ is costlyperhaps too costlybut C++ has more access (such as native threads that are not Java threads)
  - What kind of data marshalling optimizations can be performed when data marshalling to minimize system impact
- How can a stack trace be obtained from both native (C++) and Java threads.
- Can Java VM heap information be collected?
- How can network traffic be recorded globbaly in an app (with SSL inspection)?
- How can logs be collected globally?
- How can React Native be hooked? (On iOS, a lot of system points are swizzled, something that is not readily available on Android)
  - More importantly, how can JavaScriptCore be hooked? (In iOS, several JSC functions are hooked to capture data and setup RN hooks)
- What storage format to use? (Most likely sqlite for performance and ease of use)

- How to implement the mDNS behavior in the Profiler framework?
  - This has a relation to the C++ vs Java discussion in bullet 1
- What protocol should be used for live data recording? (On iOS, Plist data is passed over a raw BSD socketa good performance/ease of use ratio)
  - Would this mechanism/protocol be faster to implement in C++ or in Java?

The second section is related to live recording, but that can be looked at later (still, a chosen solution will need to account for the challenges in live recording).

Those are the issues I could come up with on the stop. I'm sure there are more challenges.

Let me know what you think.

**Comment by filipef101** [comment]
Any news about this?

**Comment by LeoNatan** [comment]
Unfortunately, not likely to happen soon. Sorry

**Comment by thegitparticle** [comment]
any alternatives that can be used for android?

**Comment by zhouzh1** [comment]
@LeoNatan Hi, is there any news for this topic?

**Comment by LeoNatan** [comment]
Considering I am no longer at Wix for two years now, and I am a macOS/iOS engineer, what news do you expect from me?

**Comment by Softverovich** [comment]
> Considering I am no longer at Wix for two years now, and I am a macOS/iOS engineer, what news do you expect from me?

Ouch.

**Comment by zhouzh1** [comment]
> Considering I am no longer at Wix for two years now, and I am a macOS/iOS engineer, what news do you expect from me?

Aha~, sorry, I don't know it, I just want to know what's the progress of Android support of the DetoxInstrument. :)

**Comment by LeoNatan** [comment]
It takes seconds to look at the state of the repo. Nobody is maintaining it since I left.
